
Vagrant.configure("2") do |config|
  num_workers = 3
  (0..num_workers).each do |i|
    name = i == 0 ? "master" : "worker#{i}"
    config.vm.define name, primary: true do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.hostname = name
      node.vm.network :private_network, ip: "192.168.56.8#{i}"
      node.vm.network :forwarded_port, guest: 22, host: 10100 + i, id: "ssh"

      node.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", i == 0 ? "2" : "1"]  
      end
      node.vm.provision "shell", path: "./install.sh"
      # node.trigger.after :up, :provision do |trigger|
      #   trigger.info = "Executing postinstall..."
      #   trigger.run_remote = { path: "./post-install.sh", args: [ num_workers ] }
      # end
    end
  end

end
