apiVersion: v1
kind: Namespace
metadata:
  name: kubeintro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: kubeintro
  labels:
    app: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: 192.168.56.1:5000/kubeintro-sample-app:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

---
kind: Service
apiVersion: v1
metadata:
  name: sample-app-service
  namespace: kubeintro
spec:
  type: ClusterIP
  selector:
    app: sample-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080